#!/usr/bin/env bash
# This script installs and configures nginx on a server

# Gets most recent package listings and installs nginx
sudo apt-get update
sudo apt-get install nginx -y

# Create string in index page
echo 'Holberton School' | sudo tee /var/www/html/index.html

# Restart nginx service
sudo service nginx restart
