#!/usr/bin/env bash
# This script configures a redirection on an nginx server

# Gets most recent package listings and installs nginx
sudo apt-get update
sudo apt-get install nginx -y

# Create string in index page
echo 'Holberton School' | sudo tee /var/www/html/index.html

# Replace string with new string in nginx conf file
new_string="\\\n\tserver {\n\t\tserver_name 35.231.117.82;\n\t\trewrite ^/redirect_me https://www.youtube.com/watch?v=QH2-TGUlwu4 permanent;\n\t}"

sudo sed -i "25i$new_string" /etc/nginx/nginx.conf

# Restart nginx service
sudo service nginx restart
