#!/usr/bin/env bash
# This script configures a redirection on an nginx server

# Gets most recent package listings and installs nginx
sudo apt-get update
sudo apt-get install nginx -y

# Create string in index page
echo 'Holberton School' | sudo tee /var/www/html/index.html

# Replace string with new string in nginx conf file
new_string="\\\n\trewrite ^/redirect_me https://www.youtube.com/watch?v=QH2-TGUlwu4 permanent;"
sudo sed -i "48i $new_string" /etc/nginx/sites-available/default

# Create custom 404 page and redirect to it
echo "Ceci n'est pas une page" | sudo tee /usr/share/nginx/html/custom_404.html
msg_404="\\\terror_page 404 /custom_404.html;\n\tlocation =/custom_404.html {\n\t\troot /usr/share/nginx/html;\n\t\tinternal;\n\t}"
sudo sed -i "50i $msg_404" /etc/nginx/sites-available/default

# Restart nginx service
sudo service nginx restart

