#!/usr/bin/env bash
# This script:
# 	Creates the file /var/run/holbertonscript.pid containing its PID
# 	Displays To infinity and beyond indefinitely
# 	Displays I hate the kill command when receiving a SIGTERM signal
# 	Displays Y U no love me?! when receiving a SIGINT signal
# 	Deletes the file /var/run/holbertonscript.pid and terminates itself 
# 		when receiving a SIGQUIT or SIGTERM signal

file="/var/run/holbertonscript.pid"

echo $$ > "$file"

while :
do
	echo "To infinity and beyond"
	sleep 2
	
	trap 'echo "I hate the kill command"; rm -rf "$file"; exit' SIGTERM
	trap 'echo "Y U n love me?!"' SIGINT
	trap 'rm -rf "$file"; exit' SIGQUIT
done
